/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author sofia
 */
public class MenuVista extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public MenuVista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        pnlPrincipal = new javax.swing.JPanel();
        MenuLateral = new javax.swing.JPanel();
        btnmtSec = new javax.swing.JButton();
        btnAcercade = new javax.swing.JButton();
        btnmtProf = new javax.swing.JButton();
        lblLogo = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        btnCerrarsesion = new javax.swing.JButton();
        pnlBarraHorizontal = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lblRol = new javax.swing.JLabel();
        lblNombreUsuario = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlPrincipal.setBackground(new java.awt.Color(255, 255, 255));

        MenuLateral.setBackground(new java.awt.Color(252, 251, 251));

        btnmtSec.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 18)); // NOI18N
        btnmtSec.setForeground(new java.awt.Color(48, 100, 124));
        btnmtSec.setText("Mantenimiento secciones");
        btnmtSec.setBorder(null);
        btnmtSec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmtSecActionPerformed(evt);
            }
        });

        btnAcercade.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 18)); // NOI18N
        btnAcercade.setForeground(new java.awt.Color(48, 100, 124));
        btnAcercade.setText("Acerca de");
        btnAcercade.setBorder(null);
        btnAcercade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcercadeActionPerformed(evt);
            }
        });

        btnmtProf.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 18)); // NOI18N
        btnmtProf.setForeground(new java.awt.Color(48, 100, 124));
        btnmtProf.setText("Mantenimiento profesores");
        btnmtProf.setBorder(null);
        btnmtProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmtProfActionPerformed(evt);
            }
        });

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Img/aula (1).png"))); // NOI18N

        lblTitulo.setFont(new java.awt.Font("Montserrat Black", 0, 18)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(48, 100, 124));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Gestión de prof. y secciones");

        btnCerrarsesion.setBackground(new java.awt.Color(48, 100, 124));
        btnCerrarsesion.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 18)); // NOI18N
        btnCerrarsesion.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrarsesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Img/log-out-circle-regular-24.png"))); // NOI18N
        btnCerrarsesion.setText("Cerrar sesión");
        btnCerrarsesion.setBorder(null);

        javax.swing.GroupLayout MenuLateralLayout = new javax.swing.GroupLayout(MenuLateral);
        MenuLateral.setLayout(MenuLateralLayout);
        MenuLateralLayout.setHorizontalGroup(
            MenuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnmtProf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
            .addComponent(btnAcercade, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(MenuLateralLayout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(lblLogo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(btnCerrarsesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnmtSec, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        MenuLateralLayout.setVerticalGroup(
            MenuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLateralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLogo)
                .addGap(73, 73, 73)
                .addComponent(btnAcercade, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnmtProf, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnmtSec, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                .addComponent(btnCerrarsesion, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlBarraHorizontal.setBackground(new java.awt.Color(252, 251, 251));

        jLabel4.setFont(new java.awt.Font("Montserrat Medium", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(48, 100, 124));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Img/user-circle-regular-24.png"))); // NOI18N

        lblRol.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 18)); // NOI18N
        lblRol.setForeground(new java.awt.Color(153, 153, 153));
        lblRol.setText("Administrador");

        lblNombreUsuario.setFont(new java.awt.Font("Montserrat Medium", 0, 18)); // NOI18N
        lblNombreUsuario.setForeground(new java.awt.Color(48, 100, 124));
        lblNombreUsuario.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNombreUsuario.setText("Nombre de usuario");

        javax.swing.GroupLayout pnlBarraHorizontalLayout = new javax.swing.GroupLayout(pnlBarraHorizontal);
        pnlBarraHorizontal.setLayout(pnlBarraHorizontalLayout);
        pnlBarraHorizontalLayout.setHorizontalGroup(
            pnlBarraHorizontalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBarraHorizontalLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblRol)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 204, Short.MAX_VALUE)
                .addComponent(lblNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addContainerGap())
        );
        pnlBarraHorizontalLayout.setVerticalGroup(
            pnlBarraHorizontalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBarraHorizontalLayout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(0, 6, Short.MAX_VALUE))
            .addGroup(pnlBarraHorizontalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBarraHorizontalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreUsuario)
                    .addComponent(lblRol))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addComponent(MenuLateral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlBarraHorizontal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MenuLateral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addComponent(pnlBarraHorizontal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnmtProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmtProfActionPerformed
            
    }//GEN-LAST:event_btnmtProfActionPerformed

    private void btnmtSecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmtSecActionPerformed
        
    }//GEN-LAST:event_btnmtSecActionPerformed

    private void btnAcercadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcercadeActionPerformed
      
    }//GEN-LAST:event_btnAcercadeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
    }
       

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MenuLateral;
    public javax.swing.JButton btnAcercade;
    public javax.swing.JButton btnCerrarsesion;
    public javax.swing.JButton btnmtProf;
    public javax.swing.JButton btnmtSec;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblLogo;
    public javax.swing.JLabel lblNombreUsuario;
    private javax.swing.JLabel lblRol;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlBarraHorizontal;
    private javax.swing.JPanel pnlPrincipal;
    // End of variables declaration//GEN-END:variables
}
